// THE 8080 STATUS WORD IS THE CPU'S, AND THE CPU IS WHERE IT IS GENERATED.
//
// The front panel displays the eight status lines the processor asserts at the start of
// every machine cycle (Status8080 in core/bus.h). Five bits fall out of the cycle type;
// M1 (opcode fetch) and STACK (a stack machine cycle) do NOT -- an opcode fetch and an
// operand read are both memory reads, a push and any other write are both memory writes.
// So the CPU passes the whole word to the bus, and this test reads it back off the bus
// observer -- the same stream the panel's snoop() sees -- one machine cycle at a time.
//
// Two guards matter most and are easy to get wrong:
//   * an operand read must NOT light M1 (only the opcode byte does), and
//   * a Z80 must NEVER light STACK -- the part has no stack-status output, so its
//     push/pop are ordinary memory cycles even though the 8080's are not.

#include "test.h"

#include "boards/s100-memory.h"
#include "core/bus.h"
#include "core/machine.h"
#include "cpu/cpu8080.h"
#include "cpu/cpuZ80.h"

#include <vector>

using namespace altair;

namespace {

// The named 8080 machine-cycle status words (Status8080 in core/bus.h).
constexpr uint8_t W_FETCH  = StM1 | StMemR | StWo;    // 0xA2 opcode fetch (M1)
constexpr uint8_t W_READ   = StMemR | StWo;           // 0x82 operand / data read
constexpr uint8_t W_WRITE  = 0;                       // 0x00 memory write (WO* low)
constexpr uint8_t W_SREAD  = StMemR | StStack | StWo; // 0x86 stack read (POP/RET)
constexpr uint8_t W_SWRITE = StStack;                 // 0x04 stack write (PUSH/CALL)
constexpr uint8_t W_IN     = StInp | StWo;            // 0x42 input
constexpr uint8_t W_OUT    = StOut;                   // 0x10 output

// Captures every settled bus cycle -- exactly what the front panel's snoop() gets.
struct Cap {
    std::vector<BusCycle> cyc;
    Bus* bus = nullptr;
    int handle = -1;
    void attach(Bus& b) {
        bus = &b;
        handle = b.observe([this](const BusCycle& c) { cyc.push_back(c); });
    }
    ~Cap() { if (bus && handle >= 0) bus->unobserve(handle); }
    void clear() { cyc.clear(); }

    // The first captured cycle of a given type -- the setup writes are already flushed.
    const BusCycle* first(Cycle t) const {
        for (const auto& c : cyc) if (c.type == t) return &c;
        return nullptr;
    }
};

MemoryBoard* addRam(Machine& m) {
    std::string err;
    auto* mem = dynamic_cast<MemoryBoard*>(m.add("memory", "mem0", err));
    Region r; r.kind = RegionKind::Ram; r.at = 0; r.size = 0x10000;
    mem->addRegion(r, err);
    setProperty(*mem, "fill", "zero", err);
    mem->power();
    return mem;
}

// A one-instruction-at-a-time program common to both cores (pure 8080 subset, so it is
// valid Z80 too). Data lives at 0x0300; the stack is set well clear of it.
//   3E 55        MVI A,55h        opcode fetch + one operand read
//   32 00 03     STA 0300h        fetch + two operands + a memory WRITE
//   3A 00 03     LDA 0300h        fetch + two operands + a memory READ
//   F5           PUSH PSW/AF      fetch + two stack WRITES
//   F1           POP  PSW/AF      fetch + two stack READS
//   D3 10        OUT (10h),A      fetch + one operand + an I/O WRITE
//   DB 10        IN  A,(10h)      fetch + one operand + an I/O READ
const std::initializer_list<uint8_t> kProgram = {
    0x3E, 0x55, 0x32, 0x00, 0x03, 0x3A, 0x00, 0x03,
    0xF5, 0xF1, 0xD3, 0x10, 0xDB, 0x10,
};

} // namespace

void test_status() {
    SECTION("the 8080/Z80 status word -- generated by the CPU, read off the bus");

    // ---- 8080: M1 on the fetch, STACK on push/pop, and the plain words between ----
    {
        Machine m;
        addRam(m);
        std::string err;
        m.add("8080", "cpu0", err);
        auto* cpu = dynamic_cast<Cpu8080*>(m.cpu());
        cpu->reset(Reset::PowerOn);
        for (const RegDef& r : cpu->registers()) if (r.name == "SP") r.set(0x8000);

        { uint16_t a = 0; for (uint8_t b : kProgram) m.bus.memWrite(a++, b); }

        Cap cap; cap.attach(m.bus);

        // MVI A,55h -- the first cycle is the M1 fetch; the second is the operand.
        cap.clear(); m.master()->step(m.bus);
        CHECK(cap.cyc.size() >= 2, "MVI runs a fetch and an operand read");
        CHECK(cap.cyc[0].status == W_FETCH, "8080 opcode fetch asserts M1 (0xA2)");
        CHECK((cap.cyc[0].status & StM1) != 0, "...M1 is set on the fetch");
        CHECK(cap.cyc[1].status == W_READ, "the immediate operand is a plain read (0x82)");
        CHECK((cap.cyc[1].status & StM1) == 0, "...and does NOT light M1");

        // STA 0300h -- ends in a memory write with no STACK bit.
        cap.clear(); m.master()->step(m.bus);
        const BusCycle* wr = cap.first(Cycle::MemWrite);
        CHECK(wr && wr->addr == 0x0300, "STA writes 0x0300");
        CHECK(wr && wr->status == W_WRITE, "a data write is 0x00 -- WO* low, no STACK");

        // LDA 0300h -- a plain data read.
        cap.clear(); m.master()->step(m.bus);
        bool sawData = false;
        for (const auto& c : cap.cyc)
            if (c.type == Cycle::MemRead && c.addr == 0x0300)
                { sawData = (c.status == W_READ); }
        CHECK(sawData, "LDA reads 0x0300 as a plain read (0x82)");

        // PUSH PSW -- the two stack writes assert STACK.
        cap.clear(); m.master()->step(m.bus);
        const BusCycle* sw = cap.first(Cycle::MemWrite);
        CHECK(sw && sw->status == W_SWRITE, "8080 PUSH is a stack write (0x04, STACK set)");
        CHECK(sw && (sw->status & StStack) != 0, "...STACK is lit");

        // POP PSW -- the two stack reads assert STACK. The instruction's FIRST memory
        // read is the M1 opcode fetch (a fetch is a read too), so skip it and look at
        // the stack read that follows.
        cap.clear(); m.master()->step(m.bus);
        const BusCycle* sr = nullptr;
        for (const auto& c : cap.cyc)
            if (c.type == Cycle::MemRead && (c.status & StM1) == 0) { sr = &c; break; }
        CHECK(sr && sr->status == W_SREAD, "8080 POP is a stack read (0x86, STACK set)");

        // OUT (10h),A -- an I/O write.
        cap.clear(); m.master()->step(m.bus);
        const BusCycle* ow = cap.first(Cycle::IoWrite);
        CHECK(ow && ow->port() == 0x10 && ow->status == W_OUT, "OUT asserts the OUT word (0x10)");

        // IN A,(10h) -- an I/O read.
        cap.clear(); m.master()->step(m.bus);
        const BusCycle* ir = cap.first(Cycle::IoRead);
        CHECK(ir && ir->port() == 0x10 && ir->status == W_IN, "IN asserts the INP word (0x42)");
    }

    // ---- Z80: M1 fires, but STACK is NEVER set, not even on push/pop ----
    {
        Machine m;
        addRam(m);
        CpuZ80 cpu;
        cpu.reset(Reset::PowerOn);
        for (const RegDef& r : cpu.registers()) if (r.name == "SP") r.set(0x8000);

        { uint16_t a = 0; for (uint8_t b : kProgram) m.bus.memWrite(a++, b); }

        Cap cap; cap.attach(m.bus);

        // The opcode fetch still asserts M1.
        cap.clear(); cpu.step(m.bus);
        CHECK(cap.cyc.size() >= 2, "the Z80 runs a fetch and an operand read");
        CHECK(cap.cyc[0].status == W_FETCH, "Z80 opcode fetch asserts M1 (0xA2)");
        CHECK((cap.cyc[1].status & StM1) == 0, "the operand read does NOT light M1");

        // Run the rest of the program, capturing everything.
        for (int i = 0; i < 6; ++i) cpu.step(m.bus);

        // PUSH AF / POP AF are ordinary memory on a Z80 -- no STACK bit anywhere.
        bool anyStack = false;
        for (const auto& c : cap.cyc) if (c.status & StStack) anyStack = true;
        CHECK(!anyStack, "a Z80 NEVER asserts STACK -- push/pop are plain memory cycles");
    }

    // ---- The fallback is unchanged: a non-CPU cycle still gets the type-derived word ----
    {
        Machine m;
        addRam(m);
        Cap cap; cap.attach(m.bus);

        m.bus.memWrite(0x0400, 0x99);   // a monitor-style poke -- no status asserted
        CHECK(cap.cyc.back().status == W_WRITE, "an un-annotated write falls back to 0x00");
        m.bus.memRead(0x0400);
        CHECK(cap.cyc.back().status == W_READ, "an un-annotated read falls back to 0x82");
        CHECK((cap.cyc.back().status & StM1) == 0, "...and the fallback never invents M1");
    }
}
