# Generate roms_generated.cpp from roms/<NAME>/<image>.
#
# The image file is embedded byte-for-byte. This script does NOT understand
# Intel HEX and must not learn to -- the C++ side parses it with the same
# loader that backs the LOAD command (DESIGN.md 10.3.1).
#
# Inputs:  -DROMS_DIR=<dir> -DOUT=<file>

file(GLOB rom_dirs RELATIVE "${ROMS_DIR}" "${ROMS_DIR}/*")

set(body "")
set(table "")

foreach(d ${rom_dirs})
  if(NOT IS_DIRECTORY "${ROMS_DIR}/${d}")
    continue()
  endif()

  file(GLOB imgs "${ROMS_DIR}/${d}/*.HEX" "${ROMS_DIR}/${d}/*.hex"
                 "${ROMS_DIR}/${d}/*.BIN" "${ROMS_DIR}/${d}/*.bin")
  list(LENGTH imgs n)
  if(n EQUAL 0)
    continue()
  endif()
  list(GET imgs 0 img)

  string(TOLOWER "${d}" name)
  string(MAKE_C_IDENTIFIER "${name}" sym)

  get_filename_component(ext "${img}" LAST_EXT)
  string(TOLOWER "${ext}" ext)
  if(ext STREQUAL ".hex")
    set(fmt "Format::Hex")
  else()
    set(fmt "Format::Bin")
  endif()
  get_filename_component(base "${img}" NAME)

  # Bytes, verbatim.
  file(READ "${img}" hexstr HEX)
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hexstr}")
  string(LENGTH "${hexstr}" len)
  math(EXPR len "${len} / 2")

  string(APPEND body
    "static const unsigned char rom_${sym}[] = {${bytes}};\n")
  string(APPEND table
    "  { \"${name}\", \"${base}\", ${fmt}, rom_${sym}, ${len} },\n")
endforeach()

file(WRITE "${OUT}"
"// GENERATED by cmake/embed_roms.cmake -- do not edit.\n"
"#include \"core/roms.h\"\n"
"\n"
"namespace altair {\n"
"\n"
"${body}"
"\n"
"static const BuiltinRom kRoms[] = {\n"
"${table}"
"};\n"
"\n"
"std::span<const BuiltinRom> builtinRoms() {\n"
"  return std::span<const BuiltinRom>(kRoms, sizeof(kRoms) / sizeof(kRoms[0]));\n"
"}\n"
"\n"
"} // namespace altair\n")

message(STATUS "embed_roms: wrote ${OUT}")
